alloygame/urls.py
from django.contrib import admin
from django.urls import path, include, re_path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),
    path("cart/", include("cart.urls")),
    path('order/', include('order.urls')),  # 订单模块
    re_path(r"^", include("goods.urls")),
    # re_path(r"^tinymce/", include("tinymce.urls")),  # 富文本编辑器
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
    path('search/', include('haystack.urls')),  # 全文检索框架
    path('searchnewstr/', include('haystack.urls')),  # 全文检索框架

]

apps/cart/urls.py
from django.urls import re_path, path

from apps.cart.views import CartAddView, CartInfoView, CartUpdateView, CartDeleteView

app_name = 'cart'

urlpatterns = [
    re_path(r'^add$', CartAddView.as_view(), name='add'),  # 购物车记录添加
    path('', CartInfoView.as_view(), name='show'),  # 购物车页面显示
    re_path(r'^update$', CartUpdateView.as_view(), name='update'),  # 购物车记录更新
    re_path(r'^delete$', CartDeleteView.as_view(), name='delete'),  # 购物车记录删除
]

apps/goods/urls.py
from django.urls import path, include, re_path
from .views import *
from apps.goods.views import IndexView, DetailView, ListView, New_strView, NewDetailView

app_name = 'goods'

urlpatterns = [
    path("", IndexView.as_view(), name="index"),  # 首页
    path("index/", IndexView.as_view(), name="index"),  # 首页
    re_path(r'^goods/(?P<goods_id>\d+)$', DetailView.as_view(), name='detail'),  # 详情页
    re_path(r'^list/(?P<type_id>\d+)/(?P<page>\d+)$', ListView.as_view(), name='list'),  # 列表页
    path('newstr/', New_strView.as_view(), name='newstr'),
    path('newdetail/', NewDetailView.as_view(), name='newdetail')
]

apps/user/urls.py
from django.urls import path, include, re_path
from apps.user import views
from apps.user.views import RegisterView, ActiveView, LoginView, LogoutView, UserInfoView, UserOrderView, \
    UserAddressView, ChangePassword, SendCode, ImageCode, WriteView, MynewstrView

app_name = 'user'

urlpatterns = [
    re_path(r"^register/$", RegisterView.as_view(), name='register'),  # 注册
    re_path(r'^active/(?P<token>.*)$', ActiveView.as_view(), name='active'),  # 激活
    # path('login', LoginView.as_view(), name='login'),  # 登录
    re_path(r"^login/$", LoginView.as_view(), name="login"),
    path('logout', LogoutView.as_view(), name='logout'),  # 登出
    path('change_password/', ChangePassword.as_view(), name='ChangePassword'),  # 修改密码
    path('send_code/', SendCode.as_view(), name='SendCode'),  # 修改密码
    path('ImageCode/', ImageCode.as_view(), name='ImageCode'),  # 验证码图片

    path('', UserInfoView.as_view(), name='user'),  # 用户中心--信息页
    re_path(r"^order/(?P<page>\d+)/$", UserOrderView.as_view(), name='order'),
    path('address', UserAddressView.as_view(), name='address'),  # 用户中心--地址页

    path('write/', WriteView.as_view(), name='write'),  # 写文章
    path('mynewstr/', MynewstrView.as_view(), name='mynewstr')  # 我的文章



]

apps/cart/models.py
from django.db import models

# Create your models here.

apps/cart/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.views.generic import View
from django.http import JsonResponse
from django_redis import get_redis_connection
from apps.goods.models import GoodsSKU


# Create your views here.
# 添加商品到购物车:
# 1）请求方式，采用ajax post
# 如果涉及到数据的修改(新增，更新，删除), 采用post
# 如果只涉及到数据的获取，采用get
# 2) 传递参数: 商品id(sku_id) 商品数量(count)


# ajax发起的请求都在后台，在浏览器中看不到效果
# /cart/add


class CartAddView(View):
    '''购物车记录添加'''

    def post(self, request):
        '''购物车记录添加'''
        user = request.user
        if not user.is_authenticated:
            # 用户未登录
            return JsonResponse({'res': 0, 'errmsg': '请先登录'})

        # 接收数据
        sku_id = request.POST.get('sku_id')
        count = request.POST.get('count')

        # 数据校验
        if not all([sku_id, count]):
            return JsonResponse({'res': 1, 'errmsg': '数据不完整'})

        # 校验添加的商品数量
        try:
            count = int(count)
        except Exception as e:
            # 数目出错
            return JsonResponse({'res': 2, 'errmsg': '商品数目出错'})

        # 校验商品是否存在
        try:
            sku = GoodsSKU.objects.get(id=sku_id)
        except GoodsSKU.DoesNotExist:
            # 商品不存在
            return JsonResponse({'res': 3, 'errmsg': '商品不存在'})

        # 业务处理:添加购物车记录
        conn = get_redis_connection('default')
        cart_key = 'cart_%d' % user.id
        # 先尝试获取sku_id的值 -> hget cart_key 属性
        # 如果sku_id在hash中不存在，hget返回None
        cart_count = conn.hget(cart_key, sku_id)
        if cart_count:
            # 累加购物车中商品的数目
            count += int(cart_count)

        # 校验商品的库存
        if count > sku.stock:
            return JsonResponse({'res': 4, 'errmsg': '商品库存不足'})

        # 设置hash中sku_id对应的值
        # hset->如果sku_id已经存在，更新数据， 如果sku_id不存在，添加数据
        conn.hset(cart_key, sku_id, count)

        # 计算用户购物车商品的条目数
        total_count = conn.hlen(cart_key)

        # 返回应答
        return JsonResponse({'res': 5, 'total_count': total_count, 'message': '添加成功'})


# /cart/
class CartInfoView(LoginRequiredMixin, View):
    '''购物车页面显示'''

    def get(self, request):
        '''显示'''
        # 获取登录的用户
        user = request.user
        # 获取用户购物车中商品的信息
        conn = get_redis_connection('default')
        cart_key = 'cart_%d' % user.id
        # {'商品id':商品数量, ...}
        cart_dict = conn.hgetall(cart_key)

        skus = []
        # 保存用户购物车中商品的总数目和总价格
        total_count = 0
        total_price = 0
        # 遍历获取商品的信息
        for sku_id, count in cart_dict.items():
            # 根据商品的id获取商品的信息
            sku = GoodsSKU.objects.get(id=sku_id)
            # 计算商品的小计
            amount = sku.price * int(count)
            # 动态给sku对象增加一个属性amount, 保存商品的小计
            sku.amount = amount
            # 动态给sku对象增加一个属性count, 保存购物车中对应商品的数量
            sku.count = count.decode()
            # 添加
            skus.append(sku)

            # 累加计算商品的总数目和总价格
            total_count += int(count)
            total_price += amount

        # 组织上下文
        context = {'total_count': total_count,
                   'total_price': total_price,
                   'skus': skus}

        # 使用模板
        return render(request, 'cart.html', context)


# 更新购物车记录
# 采用ajax post请求
# 前端需要传递的参数:商品id(sku_id) 更新的商品数量(count)
# /cart/update
class CartUpdateView(View):
    '''购物车记录更新'''

    def post(self, request):
        '''购物车记录更新'''
        user = request.user
        if not user.is_authenticated:
            # 用户未登录
            return JsonResponse({'res': 0, 'errmsg': '请先登录'})

        # 接收数据
        sku_id = request.POST.get('sku_id')
        count = request.POST.get('count')

        # 数据校验
        if not all([sku_id, count]):
            return JsonResponse({'res': 1, 'errmsg': '数据不完整'})

        # 校验添加的商品数量
        try:
            count = int(count)
        except Exception as e:
            # 数目出错
            return JsonResponse({'res': 2, 'errmsg': '商品数目出错'})

        # 校验商品是否存在
        try:
            sku = GoodsSKU.objects.get(id=sku_id)
        except GoodsSKU.DoesNotExist:
            # 商品不存在
            return JsonResponse({'res': 3, 'errmsg': '商品不存在'})

        # 业务处理:更新购物车记录
        conn = get_redis_connection('default')
        cart_key = 'cart_%d' % user.id

        # 校验商品的库存
        if count > sku.stock:
            return JsonResponse({'res': 4, 'errmsg': '商品库存不足'})

        # 更新
        conn.hset(cart_key, sku_id, count)

        # 计算用户购物车中商品的总件数 {'1':5, '2':3}
        total_count = 0
        vals = conn.hvals(cart_key)
        for val in vals:
            total_count += int(val)

        # 返回应答
        return JsonResponse({'res': 5, 'total_count': total_count, 'message': '更新成功'})


# 删除购物车记录
# 采用ajax post请求
# 前端需要传递的参数:商品的id(sku_id)
# /cart/delete
class CartDeleteView(View):
    '''购物车记录删除'''

    def post(self, request):
        '''购物车记录删除'''
        user = request.user
        if not user.is_authenticated:
            # 用户未登录
            return JsonResponse({'res': 0, 'errmsg': '请先登录'})

        # 接收参数
        sku_id = request.POST.get('sku_id')

        # 数据的校验
        if not sku_id:
            return JsonResponse({'res': 1, 'errmsg': '无效的商品id'})

        # 校验商品是否存在
        try:
            sku = GoodsSKU.objects.get(id=sku_id)
        except GoodsSKU.DoesNotExist:
            # 商品不存在
            return JsonResponse({'res': 2, 'errmsg': '商品不存在'})

        # 业务处理:删除购物车记录
        conn = get_redis_connection('default')
        cart_key = 'cart_%d' % user.id

        # 删除 hdel
        conn.hdel(cart_key, sku_id)

        # 计算用户购物车中商品的总件数 {'1':5, '2':3}
        total_count = 0
        vals = conn.hvals(cart_key)
        for val in vals:
            total_count += int(val)

        # 返回应答
        return JsonResponse({'res': 3, 'total_count': total_count, 'message': '删除成功'})

templates/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
{% load static %}
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
{#    网页标题内容块#}
	<title>{% block title %}{% endblock title %}</title>
    <link rel="shortcut icon" href=" ../static/images/ag.ico" />
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
{# 网页顶部引入文件块#}
    {% block topfiles %}{% endblock topfiles %}
</head>
<body>
{# 网页顶部欢迎信息块 #}
{% block header_con %}
	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到合金游戏!</div>
			<div class="fr">
                {% if user.is_authenticated %}
				<div class="login_btn fl">
                    欢迎您：<em>{{ user.username }}</em>
                    <span>|</span>
                    <a href="{% url 'user:logout' %}">退出</a>
                </div>
                {% else %}
				<div class="login_btn fl">
					<a href="{% url 'user:login' %}">登录</a>
					<span>|</span>
					<a href="{% url 'user:register' %}">注册</a>
				</div>
                {% endif %}
				<div class="user_link fl">
					<span>|</span>
					<a href="{% url 'user:user' %}">用户中心</a>
					<span>|</span>
					<a href="{% url 'cart:show' %}">我的购物车</a>
					<span>|</span>
					<a href="{% url 'user:order' 1 %}">我的订单</a>
				</div>
			</div>
		</div>
	</div>
{% endblock header_con %}
{#{网页顶部搜索框块}#}
{% block search_bar %}
	<div class="search_bar clearfix">
		<a href="{% url 'goods:index' %}" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
		<div class="search_con fl">
            <form action="/search/" method="get">
                <input type="text" class="input_text fl" name="q" placeholder="搜索商品或资讯">
			    <input type="submit" class="input_btn fr" name="" value="搜索">
            </form>
		</div>
		<div class="guest_cart fr">
			<a href="{% url "cart:show" %}" class="cart_name fl">我的购物车</a>
            <div class="goods_count fl" id="show_count">{{ cart_count }}</div>
		</div>
	</div>
{% endblock search_bar %}
{# 网页主题内容块#}

{% block body %}
{% endblock body %}
	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>
		</div>
        <p>CopyRight © 2021 重庆合金游戏有限公司 All Rights Reserved</p>
		<p>电话：023-****888    渝ICP备*******8号</p>
	</div>
{% block bottom %}{% endblock bottom %}
{% block bottomfiles %}{% endblock bottomfiles %}
</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}合金游戏-首页{% endblock title %}
{% block topfiles %}
	<script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/jquery-ui.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/slide.js' %}"></script>
{% endblock topfiles %}
{% block body %}
	<div class="navbar_con">
		<div class="navbar">
			<h1 class="fl">全部商品分类</h1>
			<ul class="navlist fl">
                <li><a href="{% url 'goods:index' %}">首页</a></li>
				<li class="interval">|</li>
				<li><a href="{% url 'goods:newstr' %}">资讯</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>

	<div class="center_con clearfix">
		<ul class="subnav fl">
            {% for type in types %}
			    <li><a href="#model0{{ forloop.counter }}" class="{{ type.logo }}">{{ type.name }}</a></li>
            {% endfor %}
		</ul>
		<div class="slide fl">
			<ul class="slide_pics">
                {% for banner in goods_banners  %}
				    <li><a href="{% url 'goods:detail' banner.sku.id %}"><img src="{{ banner.image.url }}" alt="幻灯片"></a></li>
                {% endfor %}
			</ul>
			<div class="prev"></div>
			<div class="next"></div>
			<ul class="points"></ul>
		</div>
		<div class="adv fl">
            {% for banner in promotion_banners %}
			    <a href="{{ banner.url }}"><img src="{{ banner.image.url }}"></a>
            {% endfor %}
		</div>
	</div>

    {% for type in types %}
	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model0{{ forloop.counter }}">{{ type.name }}</h3>
			<div class="subtitle fl">
				<span>|</span>
                {% for banner in type.title_banners %}
				    <a href="{% url 'goods:detail' banner.sku.id  %}">{{ banner.sku.name }}</a>
				{% endfor %}
			</div>
			<a href="{% url 'goods:list' type.id 1 %}" class="goods_more fr" id="fruit_more">查看更多 ></a>
		</div>

		<div class="goods_con clearfix">
			<div class="goods_banner fl"><a href="{% url 'goods:list' type.id 1 %}"><img src="{{ type.image.url }}"></a></div>
			<ul class="goods_list fl">
                {% for banner in type.image_banners %}
				<li>
                    <h4><a href="{% url 'goods:detail' banner.sku.id  %}">{{ banner.sku.name }}</a></h4>
                    <a href="{% url 'goods:detail' banner.sku.id  %}"><img src="{{ banner.sku.image.url}}"></a>
{#					<div class="prize">¥ {{ banner.sku.price }}</div>#}
				</li>
				{% endfor %}
			</ul>
		</div>
	</div>
    {% endfor %}
{% endblock body %}

templates/mynewstr.html
<!DOCTYPE html>
<!-- 网站主语言 -->
<html lang="zh-cn">
<head>
    <!-- 网站采用的字符编码 -->
    <meta charset="utf-8">
    <!-- 网站标题 -->
    <title>我的文章</title>
    {% load static %}
    <!-- 引入bootstrap的css文件 -->
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <!-- 引入monikai.css -->
    <link rel="stylesheet" href="{% static 'md_css/monokai.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css"
          integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    <!--导入css-->
    <link rel="stylesheet" href="{% static 'common/common.css' %}">
    <link rel="stylesheet" href="{% static 'common/jquery.pagination.css' %}">
    <!-- 引入vuejs -->
    <script type="text/javascript" src="{% static 'js/vue-2.5.16.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/axios-0.18.0.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
</head>

<body>
<div id="app">
    <!-- 定义导航栏 -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">

        <div class="container">
            <!-- 导航栏商标 -->
            <div>
                <a class="navbar-brand" href="{% url 'goods:index' %}">首页</a>
                <a class="navbar-brand" href="{% url 'goods:newstr' %}">资讯页</a>
                <a class="navbar-brand" href="{% url 'user:write' %}">发布文章</a>
            </div>
            <!-- 分类 -->
            <div class="collapse navbar-collapse">
                <div>
                    <ul class="nav navbar-nav">
                        {% for cat in categories %}
                            {% if cat.id == category.id %}
                                <li class="nav-item active">
                                    <a class="nav-link mr-2" href="/user/mynewstr/?cat_id={{ cat.id }}">{{ cat.title }}</a>
                                </li>
                            {% else %}
                                <li class="nav-item">
                                    <a class="nav-link mr-2" href="/user/mynewstr/?cat_id={{ cat.id }}">{{ cat.title }}</a>
                                </li>
                            {% endif %}
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
        <!--登录/个人中心-->
    </nav>

    <!-- content -->
    <div class="container">
        <!-- 列表循环 -->
            {% for article in articles %}
                {% if article.author_id == user.id %}  <!-- 只能看自己的文章 -->
                    <div class="row mt-2">
                        <!-- 文章内容 -->
                        <!-- 标题图 -->
                        <div class="col-3">
                            <a href="{% url 'goods:newdetail' %}?id={{ article.id }}">
                                <img src="{{ article.avatar.url }}" alt="avatar" style="max-width:100%; border-radius: 20px">
                            </a>
                        </div>
                        <div class="col">
                            <!-- 栏目 -->
                            <a role="button" class="btn btn-sm mb-2 btn-warning">{{ article.category.title }}</a>
                            <!-- 标签 -->
                            <span>
                                <a class="badge badge-secondary">{{ article.tags }}</a>
                            </span>
                            <!-- 标题 -->
                            <h4>
                                <b><a href="{% url 'goods:newdetail' %}?id={{ article.id }}" style="color: black;">{{ article.title }}</a></b>
                            </h4>
                            <!-- 摘要 -->
                            <div>
                                <p style="color: gray;">
                                    {{ article.sumary }}
                                </p>
                            </div>
                            <!-- 注脚 -->
                            <p>
                                <!-- 查看、评论、时间、删除 -->
                                <span><i class="fas fa-eye" style="color: lightskyblue;"></i>{{ article.total_views }}&nbsp;&nbsp;&nbsp;</span>
                                <span><i class="fas fa-comments" style="color: yellowgreen;"></i>{{ article.comments_count }}&nbsp;&nbsp;&nbsp;</span>
                                <span><i class="fas fa-clock" style="color: pink;"></i>{{ article.created | date }}</span>
                               <a href="{% url 'user:mynewstr' %}?id={{ article.id }}"><button class="btn btn-danger btn-sm" style="margin-left: 600px">删除</button></a>
                            </p>
                        </div>
                        <hr style="width: 100%;"/>
                    </div>
                {% endif %}

                {% empty %}
                    <h3>没有发布此类过文章</h3>
            {% endfor %}

        <!-- 页码导航 -->
        <div class="pagenation" style="text-align: center">
            <div id="pagination" class="page"></div>
        </div>
    </div>
</div>
<script type="text/javascript" src="{% static 'js/jquery.pagination.min.js' %}"></script>
<script type="text/javascript">
    $(function () {
        $('#pagination').pagination({
            currentPage: {
                {
                    page_num
                }
            },
        totalPage: {
            {
                total_page
            }
        },
        callback:function (current) {

            location.href = '/?cat_id={{ category.id }}&page_size={{ page_size }}&page_num=' + current;
        }
    })
    });
</script>
</body>
</html>

templates/newdetail.html
<!DOCTYPE html>
<!-- 网站主语言 -->
<html lang="zh-cn">

<head>
    <!-- 网站采用的字符编码 -->
    <meta charset="utf-8">
    <!-- 网站标题 -->
    <title>文章详情</title>
    {% load static %}
    <!-- 引入bootstrap的css文件 -->
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <!--详情页面导入-->
{#    <script src="{% static 'ckeditor/ckeditor/' %}"></script>#}
{#    <script src="{% static "ckeditor/ckeditor/plugins/prism/lib/prism/prism_patched.min.js" %}"></script>#}

{#    <link rel="stylesheet" href="{% static 'prism/prism.css' %}">#}
    <!--导入css-->
    <link rel="stylesheet" href="{% static 'common/common.css' %}">
    <link rel="stylesheet" href="{% static 'common/jquery.pagination.css' %}">
    <!-- 引入vuejs -->
    <script type="text/javascript" src="{% static 'js/vue-2.5.16.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/axios-0.18.0.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
</head>

<body>
<div id="app">
<!-- 定义导航栏 -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <!-- 导航栏商标 -->
        <div>
            <a class="navbar-brand" href="{% url 'goods:index' %}">首页</a>
            <a class="navbar-brand" href="{% url 'goods:newstr' %}">资讯页</a>
            <a class="navbar-brand" href="{% url 'user:write' %}">发布文章</a>
        </div>
        <!-- 分类 -->
        <div class="collapse navbar-collapse" id="navbarNav">
             <div>
                <ul class="nav navbar-nav">
                    {% for cat in categories %}
                        {% if cat.id == category.id %}
                            <li class="nav-item active">
                                <a class="nav-link mr-2" href="/newstr/?cat_id={{ cat.id }}">{{ cat.title }}</a>
                            </li>
                        {% else %}
                            <li class="nav-item">
                                <a class="nav-link mr-2" href="/newstr/?cat_id={{ cat.id }}">{{ cat.title }}</a>
                            </li>
                        {% endif %}
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
    <!--登录/个人中心-->
</nav>

<!-- content -->
<div class="container">
    <div class="row">
        <!--文章详情-->
        <div class="col-9">
             <!-- 标题及作者 -->
            <h1 class="mt-4 mb-4">{{ article.title }}</h1>
            <div class="alert alert-success"><div>作者：<span>{{ article.author.username }}</span></div><div>浏览：{{ article.total_views }}</div></div>
            <!-- 文章正文 -->
            <div class="col-12" style="word-break: break-all;word-wrap: break-word;">
                {{ article.content|safe }}
            </div>
{#            {% if  %}#}
            <br>
            <!-- 发表评论 -->
            <hr>
            <br>
            <h5 class="row justify-content-center" v-show="!username">请<a href="{% url 'user:login' %}">登录</a>后回复
            </h5>
            <br>
            <div>
                <form method="POST">
                    {% csrf_token %}
                    <input type="hidden" name="id" value="{{ article.id }}">
                    <div class="form-group"><label for="body"><strong>我也要发言：</strong></label><div>

                    <div class="django-ckeditor-widget" data-field-id="id_body" style="display: inline-block;">
                        <textarea cols="40" id="id_body" name="content" rows="10" required data-processed="0" :data-config="data_config" data-external-plugin-resources="[]" data-id="id_body" data-type="ckeditortype">

                        </textarea>
                    </div>
                </div>
                </div>
                    <!-- 提交按钮 -->
                    <button type="submit" class="btn btn-primary ">发送</button>
                </form>
            </div>
            <br>
            <!-- 显示评论 -->
            <h4>共有{{ total_count }}条评论</h4>
            <div class="row">
                 {% for comment in comments %}
                    <div class="col-12" >
                            <hr><p><strong style="color: pink"></strong></p>
                            <div>
                                <div><span><strong>{{ comment.user.username }}</strong></span>&nbsp;<span style="color: gray">{{ comment.created | date:'Y:m:d H:i:s' }}</span></div>
                                <br>
                                <p>{{ comment.content|safe }}</p>
                            </div>
                </div>
                {% endfor %}
                <div class="pagenation" style="text-align: center">
                    <div id="pagination" class="page"></div>
                </div>
            </div>

        </div>
        <!-- 推荐 -->
        <div class="col-3 mt-4" id="sidebar" class="sidebar">
            <div class="sidebar__inner">
                <h4><strong>推荐</strong></h4>
                <hr>
                {% for hot_article in hot_articles %}
                    <a href="{% url 'goods:newdetail' %}?id={{ hot_article.id }}" style="color: black">{{ hot_article.title }}</a><br>
                {% endfor %}
            </div>
        </div>
    </div>
</div>

</div>

<!--ckeditor-->
<script type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>
<script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>
<!-- 引入js -->
<script type="text/javascript" src="{% static 'js/host.js' %}"></script>
<script type="text/javascript" src="{% static 'js/common.js' %}"></script>
<script type="text/javascript" src="{% static 'js/detail.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery.pagination.min.js' %}"></script>
<script type="text/javascript">
    $(function () {
        $('#pagination').pagination({
           currentPage: {{ page_num }},
            totalPage: {{ total_page }},
            callback:function (current) {
                location.href = '/newstr/detail/?id={{ article.id }}&page_size={{ page_size }}&page_num='+current;
            }
        })
    });
</script>
</body>

</html>